
cc = gcc
cflags = -O0 -g
cxx = g++
cxxflags = -O0 -g -std=c++1z
libs = `pkg-config --cflags --libs libsystemd`


p = cs
srv = $(p)d.service
bus = org.$(p)
spath = /etc/systemd/system


.SUFFIXES:


run: $(p) $(spath)/$(srv)
	sudo systemctl restart $(srv)
	make status

$(p).c.o: $(p).c
	$(cc) $(cflags) -c $< -o $@ 

$(p).cxx.o: $(p).cxx
	$(cxx) $(cxxflags) -c $< -o $@

$(p): $(p).c.o $(p).cxx.o 
	$(cxx) $(cxxflags) $^ $(libs) -o $@


jadd: jadd.cxx
	$(cxx) $(cxxflags) $^ $(libs) -o $@

status:
	sudo systemctl status $(srv)
	busctl tree $(bus)

stop:
	sudo systemctl stop $(bus).busname
	sudo systemctl stop $(srv)


clean:
	rm -f $(p) $(p).c.o $(p).cxx.o jadd


$(spath)/$(srv): $(bus).busname $(srv).in
	sed s:'ExecStart=.*':"ExecStart=${PWD}/$(p)":g $(srv).in > $(srv)
	sed -i 1i"# Do not edit this file.\n# It is generated from ${PWD}/$(srv).in\n" $(srv)
	sudo cp $(bus).busname $(srv) $(spath)/
	rm $(srv)
	sudo systemctl daemon-reload


install: $(spath)/$(srv)


uninstall:
	-sudo systemctl --now disable $(bus).busname 
	-sudo systemctl --now disable $(srv)
	sudo rm -f $(spath)/$(srv) $(spath)/$(bus).busname 
	sudo systemctl daemon-reload